import {
  Page,
  Text,
  View,
  Document,
  StyleSheet,
  Image
} from "@react-pdf/renderer";
import dayjs from "dayjs";
import atdentallogo from "../assets/atdentallogo.png";

type Props = {
  rowData: {
    rows: {
      dentistName: string;
      patientName: string;
      service: string;
      serviceCategory: string;
      price: number;
      billingDate: string;
    }[];
    dateStart: string;
    dateEnd: string;
  };
  generatedBy: UserResponse;
};

const styles = StyleSheet.create({
  header: {
    width: "100vw",
    position: "absolute",
    top: "0",
    left: "0",
    color: "white",
    fontWeight: "heavy",
    paddingHorizontal: ".5in",
    paddingTop: ".5in",
    paddingBottom: ".25in",
    backgroundColor: "#2d9cdb"
  },
  table: {
    flexDirection: "column",
    marginVertical: ".5in"
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#2d9cdb",
    width: "auto"
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1px solid #d9d9d9"
  },
  tableHeader: {
    padding: "6px",
    fontSize: "12px",
    color: "white",
    width: "1.3in",
    textAlign: "center"
  },
  tableData: {
    paddingHorizontal: "6px",
    paddingVertical: "4px",
    fontSize: "11px",
    width: "1.3in",
    textAlign: "center",
    marginVertical: "auto"
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between"
  }
});

const Report = ({ rowData, generatedBy }: Props) => {
  const totalPrice: number = rowData.rows.reduce(
    (total, data) => total + data.price,
    0
  );
  return (
    <Document>
      <Page size="LEGAL" style={{ padding: "1in" }}>
        <View style={styles.header}>
          <View
            style={{
              flexDirection: "row",
              alignItems: "center",
              gap: "8px"
            }}
          >
            <Image src={atdentallogo} style={{ height: "42px" }} />
            <Text style={{ fontSize: "32px" }}>Dental Home</Text>
          </View>
          <Text style={{ fontSize: "10px" }}>
            13 Azucena Street Andrea 1, Panapaan 6, Bacoor, Cavite.
          </Text>
        </View>
        <View>
          <Text style={{ marginTop: "1in", fontSize: "12px" }}>
            Reports from {dayjs(rowData.dateStart).format("MMMM DD YYYY")}
            {" to "}
            {dayjs(rowData.dateEnd).format("MMMM DD YYYY")}
          </Text>
          <View style={styles.table}>
            <View style={styles.tableHeaderRow}>
              <View style={styles.tableHeader}>
                <Text>Dentist</Text>
              </View>
              <View style={styles.tableHeader}>
                <Text>Patient</Text>
              </View>
              <View style={styles.tableHeader}>
                <Text>Category</Text>
              </View>
              <View style={styles.tableHeader}>
                <Text>Service</Text>
              </View>
              <View style={styles.tableHeader}>
                <Text>Price</Text>
              </View>
            </View>
            {rowData &&
              rowData.rows.map((data, i) => (
                <View key={i} style={styles.tableRow}>
                  <View style={styles.tableData}>
                    <Text>{data.dentistName}</Text>
                  </View>
                  <View style={styles.tableData}>
                    <Text>{data.patientName}</Text>
                  </View>
                  <View style={styles.tableData}>
                    <Text>{data.serviceCategory}</Text>
                  </View>
                  <View style={styles.tableData}>
                    <Text>{data.service}</Text>
                  </View>
                  <View style={styles.tableData}>
                    <Text>{"P" + data.price.toFixed(2)}</Text>
                  </View>
                </View>
              ))}
            <View style={styles.tableRow}>
              <View style={styles.tableData} />
              <View style={styles.tableData} />
              <View style={styles.tableData} />
              <View style={styles.tableData}>
                <Text>TOTAL</Text>
              </View>
              <View style={styles.tableData}>
                <Text>{"P" + totalPrice.toFixed(2)}</Text>
              </View>
            </View>
          </View>
          <View
            style={{
              marginTop: "1in",
              flexDirection: "row",
              justifyContent: "space-between"
            }}
          >
            <View style={{ flexDirection: "column", gap: ".5in" }}>
              <Text style={{ fontSize: "12px" }}>Generated by:</Text>
              <Text
                style={{
                  fontSize: "12px",
                  borderBottom: "1px solid black",
                  width: "164px",
                  textAlign: "center"
                }}
              >
                {generatedBy.name.firstName} {generatedBy.name.lastName}
              </Text>
            </View>
            <View style={{ flexDirection: "column", gap: ".5in" }}>
              <Text style={{ fontSize: "12px" }}>Generated on:</Text>
              <Text
                style={{
                  fontSize: "12px",
                  borderBottom: "1px solid black",
                  width: "164px",
                  textAlign: "center"
                }}
              >
                {dayjs().format("MMMM DD YYYY")}
              </Text>
            </View>
          </View>
        </View>
      </Page>
    </Document>
  );
};

export default Report;
